language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: cupcake-shop-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: pqKOhm6hf1H8mqQ8sehoxAb8kLuIR8K5OrCZOyGJntK4BTL9m/lURNe6jCpFglZvi4A8QkY4HwQCP5XZfDfc8HrVBQsGeLyoKNiCunB8UB2E74Rcei1f/zxYuA5gVqrIMVYv+Uwp6EMRypzCqBk99+iMvR5LWZMLRlV1d3m7H+C+88//WS+EbHJphAEV4WgCcBqetWsyJnpHYkh+GwJ/BfrHWaokuXeFgr+nX55VF+bLnZauoayvLb4t02FupjV459InzRRJMsqG+lR9IoMMtda3wnfjsOvKUxVLnFC5b1l5aBZRXPDRDc86AVfz8Qmo8cxfNynsdjUPPvit50jC6SsRNWE+ypXg/QWUgBye+ZtBnAi2SkDv6OA3V61Myxi3k+ra+JPMvpcvJf0QSJu1EH/gvEHOrbNOvAP3xkED7tENSfdEkjbJiNDreh+9KgO3V7OsENu7f2/cj6ppgmHxkvqXru99O3UJid1k2idXOYofeZExdoytXxUP8NDAgfNCx/bubcN5jXKbj+PHYNMzPftPno680ot291XKgiyTcq0SzZjenQ0MrHuOf2wJ+mchW/xyml/8IMb46zzdrx+kkIZSus5Gz4QuuR3ozj56k5GpL2svUHObQGJ6fVDdsRPgjzkVv7JZ7nRCvBqnOmuv3BSDYvItZUGglOxACGwr4yM=
